const data = {
    "success": true,
    "data": [
        {
            "_id": "674ab697ee231c5dd866d14a",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Pravinbhai",
            "middleName": "Kalyanbhai",
            "lastName": "Chaudhari",
            "gender": "Male",
            "email": "",
            "mobileNumber": 9638629623,
            "alternateMobileNumber": null,
            "workLocationState": "Andhra Pradesh",
            "workLocationArea": "Gopalapatnam",
            "workLocationSection": "Visakhapatnam (Urban)",
            "permanentAddress": {
                "address": "AT kotda forna \nTa deodar\nDist Banaskantha",
                "state": "Gujarat",
                "mandal": "Deodar",
                "village": "AT KOTDA POST FORNA",
                "pincode": 385330,
                "mandaliNearAddress": "Kotda ",
                "_id": "6756ac1577fb36158a2215ed"
            },
            "hasFiberInternet": true,
            "internetProvider": "1",
            "currentInternetPrice": 12121,
            "currentInternetPlanValidity": "1",
            "usesOTT": false,
            "wantsFreeEducationContent": false,
            "preferredPlan": "50_3_1706",
            "isDeleted": false,
            "createdAt": "2024-11-30T06:54:15.717Z",
            "updatedAt": "2024-12-09T08:36:37.840Z",
            "__v": 0,
            "wifiExpense": "100-200",
            "wifiRecharge": "1"
        },
        {
            "_id": "674ab6afee231c5dd866d14e",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "AJMALBHAI ",
            "middleName": "KALABHAI",
            "lastName": "PATEL",
            "gender": "Male",
            "email": "chaudharisuresh829@gmail.com",
            "mobileNumber": 6353107879,
            "alternateMobileNumber": 0,
            "workLocationState": "Andhra Pradesh",
            "workLocationArea": "Gopalapatnam",
            "workLocationSection": "Visakhapatnam (Urban)",
            "permanentAddress": {
                "address": "AT KHADOL PO VASRDA ",
                "state": "GUJRAT",
                "mandal": "SUIGAM",
                "village": "KHADOL",
                "pincode": 385575,
                "mandaliNearAddress": "KHADOL SEVASHKARAI DUDH UTPADAK MANDALI",
                "_id": "67559c6d77fb36158a221579"
            },
            "hasFiberInternet": true,
            "internetProvider": "1",
            "currentInternetPrice": 6554,
            "currentInternetPlanValidity": "3",
            "usesOTT": false,
            "wantsFreeEducationContent": false,
            "preferredPlan": "50_12_7066",
            "isDeleted": false,
            "createdAt": "2024-11-30T06:54:39.599Z",
            "updatedAt": "2024-12-08T13:17:33.216Z",
            "__v": 0,
            "wifiExpense": "200-500",
            "wifiRecharge": "1"
        },
        {
            "_id": "674b1ccaee231c5dd866d176",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": " PRAKASH KUMAR ",
            "middleName": "CHANDULAL ",
            "lastName": "PANDYA ",
            "email": "prakash.c.pandya84@gmail.com",
            "mobileNumber": 9913536212,
            "alternateMobileNumber": 6355355843,
            "permanentAddress": {
                "address": "AT.LIMBOI.TA.VADGAM.PO.MEMDPUAR",
                "state": "Gujarat",
                "mandal": "VADGAM ",
                "village": "BRAHMAN VASA",
                "pincode": 385422,
                "mandaliNearAddress": "Limboi Milk Society ",
                "_id": "6756a42e77fb36158a2215d0"
            },
            "hasFiberInternet": true,
            "internetProvider": "1",
            "currentInternetPrice": 545,
            "currentInternetPlanValidity": "1",
            "usesOTT": false,
            "wantsFreeEducationContent": false,
            "preferredPlan": "20_3_1059",
            "isDeleted": false,
            "createdAt": "2024-11-30T14:10:18.199Z",
            "updatedAt": "2024-12-09T08:02:54.410Z",
            "__v": 0,
            "wifiExpense": "100-200",
            "wifiRecharge": "1"
        },
        {
            "_id": "6756aec9e00b8ba21e409b87",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Baldev Bhai ",
            "middleName": "LAKHABHAI ",
            "lastName": "Desai ",
            "email": "rabarib818@gmail.com",
            "mobileNumber": 8238658248,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Rabari vas, bhilot ",
                "state": "Gujarat ",
                "mandal": "Radhnpur ",
                "village": "Bhilot ",
                "pincode": 385340,
                "mandaliNearAddress": "ભીલોટ દુધ મંડળી ",
                "_id": "6756aec9e00b8ba21e409b88"
            },
            "internetProvider": "1",
            "wifiExpense": "500-1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T08:48:09.035Z",
            "updatedAt": "2024-12-09T08:48:09.035Z",
            "__v": 0
        },
        {
            "_id": "6756aec9e00b8ba21e409b8a",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Baldev Bhai ",
            "middleName": "LAKHABHAI ",
            "lastName": "Desai ",
            "email": "rabarib818@gmail.com",
            "mobileNumber": 8238658248,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Rabari vas, bhilot ",
                "state": "Gujarat ",
                "mandal": "Radhnpur ",
                "village": "Bhilot ",
                "pincode": 385340,
                "mandaliNearAddress": "ભીલોટ દુધ મંડળી ",
                "_id": "6756aec9e00b8ba21e409b8b"
            },
            "internetProvider": "1",
            "wifiExpense": "500-1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T08:48:09.496Z",
            "updatedAt": "2024-12-09T08:48:09.496Z",
            "__v": 0
        },
        {
            "_id": "6756aee7e00b8ba21e409b8d",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Kirankumar",
            "middleName": "J",
            "lastName": "Chaudhary ",
            "email": "",
            "mobileNumber": 8200039500,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "62,Bansidhar society, near govinda school, dairy road",
                "state": "Gujarat",
                "mandal": "Palanpur ",
                "village": "Palanpur",
                "pincode": 385001,
                "mandaliNearAddress": "",
                "_id": "6756aee7e00b8ba21e409b8e"
            },
            "internetProvider": "1",
            "wifiExpense": "above 1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T08:48:39.536Z",
            "updatedAt": "2024-12-09T08:48:39.536Z",
            "__v": 0
        },
        {
            "_id": "6756b239e00b8ba21e409b90",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Pravinbhai",
            "middleName": "Premajibhai",
            "lastName": "Chaudhary",
            "email": "pravinchaudhary015@gmail.com",
            "mobileNumber": 9428675850,
            "alternateMobileNumber": 9428675850,
            "permanentAddress": {
                "address": "At: Aegola, Po: Chadotar, Ta: Palanpur, Dist: Banaskantha",
                "state": "Gujarat",
                "mandal": "palanpur",
                "village": "Aegola",
                "pincode": 385001,
                "mandaliNearAddress": "Dudh Ganga Aegola",
                "_id": "6756b239e00b8ba21e409b91"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T09:02:49.231Z",
            "updatedAt": "2024-12-09T09:02:49.231Z",
            "__v": 0
        },
        {
            "_id": "6756bc6ce00b8ba21e409b93",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Pravin bhai",
            "middleName": "Dalji Bhai",
            "lastName": "Patel",
            "email": "pdpatel@banasdairy.coop",
            "mobileNumber": 9429407065,
            "alternateMobileNumber": 9664652737,
            "permanentAddress": {
                "address": "Madhvas ,At & Po. - Jalotra , Ta. Vadgam ,Dist. - Banaskantha\n",
                "state": "Gujrat",
                "mandal": "Vadgam",
                "village": "Village",
                "pincode": 385001,
                "mandaliNearAddress": "Jalotra Milk producers Society",
                "_id": "6756bc6ce00b8ba21e409b94"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T09:46:20.066Z",
            "updatedAt": "2024-12-09T09:46:20.066Z",
            "__v": 0
        },
        {
            "_id": "6756c106e00b8ba21e409b96",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Vashrambhai ",
            "middleName": "Nagajibhai ",
            "lastName": "Patel",
            "email": "vashrambhaipatel9@gmail.com",
            "mobileNumber": 9979413553,
            "alternateMobileNumber": 9624818245,
            "permanentAddress": {
                "address": "AT.- Umedpura,Ta.- vav, Dist -Banaskantha ",
                "state": "Gujarat",
                "mandal": "Vav",
                "village": "Umedpura",
                "pincode": 385566,
                "mandaliNearAddress": "Umedpura",
                "_id": "6756c106e00b8ba21e409b97"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T10:05:58.601Z",
            "updatedAt": "2024-12-09T10:05:58.601Z",
            "__v": 0
        },
        {
            "_id": "6756c2fde00b8ba21e409b99",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "CHANDRAKANT  SHARMA",
            "middleName": "",
            "lastName": "SHARMA",
            "email": "",
            "mobileNumber": 9140970827,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "121 Akshtam Saptam, Gathaman Road, Palanpur",
                "state": "Gujarat",
                "mandal": "Palanpur",
                "village": "Gathaman Road",
                "pincode": 385001,
                "mandaliNearAddress": "",
                "_id": "6756c2fde00b8ba21e409b9a"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T10:14:21.319Z",
            "updatedAt": "2024-12-09T10:14:21.319Z",
            "__v": 0
        },
        {
            "_id": "6756ca75e00b8ba21e409b9c",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Kailash Ojha",
            "middleName": "N L Ojha",
            "lastName": "Ojha",
            "email": "kailash.ojha@banasdairy.coop",
            "mobileNumber": 8800100465,
            "alternateMobileNumber": 9560570198,
            "permanentAddress": {
                "address": "Plot No- B1, CG City, Chakganjaria, Sultanpur Road",
                "state": "Uttar Pradesh",
                "mandal": "Lucknow",
                "village": "Lucknow",
                "pincode": 226017,
                "mandaliNearAddress": "",
                "_id": "6756ca75e00b8ba21e409b9d"
            },
            "internetProvider": "12",
            "wifiExpense": "500-1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T10:46:13.919Z",
            "updatedAt": "2024-12-09T10:46:13.919Z",
            "__v": 0
        },
        {
            "_id": "6756cc6ce00b8ba21e409b9f",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Vashrambhai ",
            "middleName": "Nagjibhai",
            "lastName": "Patel",
            "email": "vashrambhaipatel9@gmail.com",
            "mobileNumber": 9979413553,
            "alternateMobileNumber": 9624818245,
            "permanentAddress": {
                "address": "AT.- Umedpura,Ta.- Vav, Dist. Banaskantha ",
                "state": "Gujarat",
                "mandal": "Vav",
                "village": "Umedpura ",
                "pincode": 385566,
                "mandaliNearAddress": "Umedpura ",
                "_id": "6756cc6ce00b8ba21e409ba0"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "3",
            "createdAt": "2024-12-09T10:54:36.058Z",
            "updatedAt": "2024-12-09T10:54:36.058Z",
            "__v": 0
        },
        {
            "_id": "6756d2f2e00b8ba21e409ba2",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "karshan",
            "middleName": "sagthabhai",
            "lastName": "chaudhary",
            "email": "kschaudhary3@gmail.com",
            "mobileNumber": 9427390001,
            "alternateMobileNumber": 9712104121,
            "permanentAddress": {
                "address": "govinda satetas sosayti",
                "state": "gujraj",
                "mandal": "palanpur",
                "village": "palanpur",
                "pincode": 385000,
                "mandaliNearAddress": "",
                "_id": "6756d2f2e00b8ba21e409ba3"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T11:22:26.859Z",
            "updatedAt": "2024-12-09T11:22:26.859Z",
            "__v": 0
        },
        {
            "_id": "6756d46de00b8ba21e409ba5",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "KALPESHKUMAR",
            "middleName": "FALJIBHAI",
            "lastName": "CHAUDHARY",
            "email": "kalpeshfmtech@gmail.com",
            "mobileNumber": 9303285618,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "B29 AKSHATAM4\nNEAR MEDIPOLIS\nDEESA HIGHWAY\nPALANPUR",
                "state": "GUJARAT",
                "mandal": "PALANPUR",
                "village": "AKESAN",
                "pincode": 385001,
                "mandaliNearAddress": "AKESAN",
                "_id": "6756d46de00b8ba21e409ba6"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "12",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T11:28:45.851Z",
            "updatedAt": "2024-12-09T11:28:45.851Z",
            "__v": 0
        },
        {
            "_id": "6756d54fe00b8ba21e409ba8",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "VIKRAM ",
            "middleName": "KANTILAL ",
            "lastName": "PANDYA",
            "email": "vikrampandya143@gmail.com",
            "mobileNumber": 7600930150,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "GANESHPURA PALANPUR ",
                "state": "GUJARAT ",
                "mandal": "PALANPUR ",
                "village": "GANESHPURA ",
                "pincode": 385001,
                "mandaliNearAddress": "GANESHPURA ",
                "_id": "6756d54fe00b8ba21e409ba9"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T11:32:31.205Z",
            "updatedAt": "2024-12-09T11:32:31.205Z",
            "__v": 0
        },
        {
            "_id": "6756d735e00b8ba21e409bab",
            "employeeId": "milk-pourer",
            "title": "Mrs.",
            "firstName": "Dudabhai ",
            "middleName": "Bhikhabhai",
            "lastName": "Rajput",
            "email": "duda.rajput@gmail.com",
            "mobileNumber": 9624956848,
            "alternateMobileNumber": 8154828213,
            "permanentAddress": {
                "address": "At gela post lakhani dist b.k",
                "state": "Gujrat",
                "mandal": "Lakhani",
                "village": "Gela",
                "pincode": 385581,
                "mandaliNearAddress": "Gela golia dudh mndali gela",
                "_id": "6756d735e00b8ba21e409bac"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T11:40:37.570Z",
            "updatedAt": "2024-12-09T11:40:37.570Z",
            "__v": 0
        },
        {
            "_id": "6756d96ae00b8ba21e409bae",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "PRAKASHKUMAR ",
            "middleName": "CHANDULAL ",
            "lastName": "PANDYA ",
            "email": "prakash.c.pandya84@gmail.com",
            "mobileNumber": 9913536212,
            "alternateMobileNumber": 6355355843,
            "permanentAddress": {
                "address": "GUJARAT\nLIMBOI",
                "state": "Gujarat",
                "mandal": "VADGAM ",
                "village": "LIMBOI ",
                "pincode": 385421,
                "mandaliNearAddress": "LIMBOI ",
                "_id": "6756d96ae00b8ba21e409baf"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T11:50:02.899Z",
            "updatedAt": "2024-12-09T11:50:02.899Z",
            "__v": 0
        },
        {
            "_id": "6756d9f3e00b8ba21e409bb1",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Jaydevbhai",
            "middleName": "Rajaram",
            "lastName": "Joshi",
            "email": "jaydevjoshi96@gmail.com",
            "mobileNumber": 9979369348,
            "alternateMobileNumber": 9725469348,
            "permanentAddress": {
                "address": "Nani",
                "state": "Gujrat",
                "mandal": "Lakhani",
                "village": "Nani",
                "pincode": 385310,
                "mandaliNearAddress": "Nani",
                "_id": "6756d9f3e00b8ba21e409bb2"
            },
            "internetProvider": "2",
            "wifiExpense": "200-500",
            "wifiRecharge": "2",
            "currentInternetPlanValidity": "2",
            "createdAt": "2024-12-09T11:52:19.611Z",
            "updatedAt": "2024-12-09T11:52:19.611Z",
            "__v": 0
        },
        {
            "_id": "6756dbe6e00b8ba21e409bb4",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Babubhai",
            "middleName": "Galbabhai",
            "lastName": "Patel",
            "email": "breejchaudhary12345@gmail.com",
            "mobileNumber": 9426961700,
            "alternateMobileNumber": 8077832406,
            "permanentAddress": {
                "address": "Village Ambetha Ta Palanpur Dist Banaskantha Post Lokniketan Ratanpur",
                "state": "Gujarat",
                "mandal": "Palanpur",
                "village": "Ambetha",
                "pincode": 385001,
                "mandaliNearAddress": "Ambetha Dudha Mandali",
                "_id": "6756dbe6e00b8ba21e409bb5"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "3",
            "createdAt": "2024-12-09T12:00:38.682Z",
            "updatedAt": "2024-12-09T12:00:38.682Z",
            "__v": 0
        },
        {
            "_id": "6756dcb1e00b8ba21e409bb7",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "Bhemabhai",
            "middleName": "Ratnabhai",
            "lastName": "Chaudhary",
            "email": "",
            "mobileNumber": 9824413299,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Gosan",
                "state": "Gujarat ",
                "mandal": "Bhabhar",
                "village": "Gosan",
                "pincode": 385320,
                "mandaliNearAddress": "Gosan",
                "_id": "6756dcb1e00b8ba21e409bb8"
            },
            "internetProvider": "6",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:04:01.965Z",
            "updatedAt": "2024-12-09T12:04:01.965Z",
            "__v": 0
        },
        {
            "_id": "6756dd37e00b8ba21e409bba",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Parbatbhai ",
            "middleName": "Amichandji ",
            "lastName": "Tha",
            "email": "thakorparbat215@gmail.com",
            "mobileNumber": 8140243215,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Dodiya ",
                "state": "Gujrat ",
                "mandal": "Lakhani ",
                "village": "Dodiya ",
                "pincode": 385565,
                "mandaliNearAddress": "Dodiya du.u.s.m.li.",
                "_id": "6756dd37e00b8ba21e409bbb"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:06:15.707Z",
            "updatedAt": "2024-12-09T12:06:15.707Z",
            "__v": 0
        },
        {
            "_id": "6756dd6ae00b8ba21e409bbd",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Kalpeshji",
            "middleName": "Keshaji",
            "lastName": "Thakoar",
            "email": "kalpeshthakor99782@gmail.com",
            "mobileNumber": 9106284934,
            "alternateMobileNumber": 9978263941,
            "permanentAddress": {
                "address": "Dodiya",
                "state": "Guojrat",
                "mandal": "Lakhani",
                "village": "Dodiya",
                "pincode": 385565,
                "mandaliNearAddress": "Dodiya",
                "_id": "6756dd6ae00b8ba21e409bbe"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:07:06.848Z",
            "updatedAt": "2024-12-09T12:07:06.848Z",
            "__v": 0
        },
        {
            "_id": "6756dd75e00b8ba21e409bc0",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "Bhemabhai ",
            "middleName": "Ratnabhai ",
            "lastName": "Chaudhary ",
            "email": "",
            "mobileNumber": 9824413299,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Gosan ",
                "state": "Gujarat ",
                "mandal": "Bhabhar",
                "village": "Gosan ",
                "pincode": 385320,
                "mandaliNearAddress": "Gosan",
                "_id": "6756dd75e00b8ba21e409bc1"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:07:17.484Z",
            "updatedAt": "2024-12-09T12:07:17.484Z",
            "__v": 0
        },
        {
            "_id": "6756dddbe00b8ba21e409bc3",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Parbatbhai ",
            "middleName": "Amichandji ",
            "lastName": "Thakor ",
            "email": "thakorparbat215@gmail.com",
            "mobileNumber": 8140243215,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Dodiya ",
                "state": "Gujrat ",
                "mandal": "Lahani ",
                "village": "Dodiya ",
                "pincode": 385565,
                "mandaliNearAddress": "dodiya du.u.s.m.li",
                "_id": "6756dddbe00b8ba21e409bc4"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "3",
            "createdAt": "2024-12-09T12:08:59.289Z",
            "updatedAt": "2024-12-09T12:08:59.289Z",
            "__v": 0
        },
        {
            "_id": "6756de21e00b8ba21e409bc6",
            "employeeId": "milk-pourer",
            "title": "Mrs.",
            "firstName": "Premananda ",
            "middleName": "Kalabhai",
            "lastName": "Solanki",
            "email": "",
            "mobileNumber": 951215629,
            "alternateMobileNumber": 951215629,
            "permanentAddress": {
                "address": "Chhapara",
                "state": "Gujarat",
                "mandal": "PAlanpur",
                "village": "Chhapara",
                "pincode": 385001,
                "mandaliNearAddress": "",
                "_id": "6756de21e00b8ba21e409bc7"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:10:09.045Z",
            "updatedAt": "2024-12-09T12:10:09.045Z",
            "__v": 0
        },
        {
            "_id": "6756df48e00b8ba21e409bc9",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "Vikramshih ",
            "middleName": "BALVANTAJI ",
            "lastName": "Rathod ",
            "email": "",
            "mobileNumber": 9737935092,
            "alternateMobileNumber": 9726809849,
            "permanentAddress": {
                "address": "Shiya dhanera ",
                "state": "Gujrat ",
                "mandal": "Dhanera ",
                "village": "Shiya ",
                "pincode": 385310,
                "mandaliNearAddress": "Shiya ",
                "_id": "6756df48e00b8ba21e409bca"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:15:04.212Z",
            "updatedAt": "2024-12-09T12:15:04.212Z",
            "__v": 0
        },
        {
            "_id": "6756e017e00b8ba21e409bcc",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "HiteshKumar ",
            "middleName": "Dhengabhai",
            "lastName": "Rabari",
            "email": "",
            "mobileNumber": 9978716508,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Agathala",
                "state": "Gujarat ",
                "mandal": "Lakhani",
                "village": "Agathala ",
                "pincode": 385535,
                "mandaliNearAddress": "Aagathala dhuth madali",
                "_id": "6756e017e00b8ba21e409bcd"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:18:31.547Z",
            "updatedAt": "2024-12-09T12:18:31.547Z",
            "__v": 0
        },
        {
            "_id": "6756e100e00b8ba21e409bcf",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "gordhanbhai ",
            "middleName": "Dharmshibhai ",
            "lastName": "Patel",
            "email": "",
            "mobileNumber": 9429308097,
            "alternateMobileNumber": 9429308097,
            "permanentAddress": {
                "address": "Jasra",
                "state": "Gujrat ",
                "mandal": "Lakhani ",
                "village": "Jasra",
                "pincode": 385535,
                "mandaliNearAddress": "Chaudhary vas jasra ",
                "_id": "6756e100e00b8ba21e409bd0"
            },
            "internetProvider": "3",
            "wifiExpense": "500-1000",
            "wifiRecharge": "3",
            "currentInternetPlanValidity": "3",
            "createdAt": "2024-12-09T12:22:24.400Z",
            "updatedAt": "2024-12-09T12:22:24.400Z",
            "__v": 0
        },
        {
            "_id": "6756e210e00b8ba21e409bd2",
            "employeeId": "none",
            "title": "Dr.",
            "firstName": "Haradanji",
            "middleName": "Venaji",
            "lastName": "Chudhary ",
            "email": "",
            "mobileNumber": 9724219114,
            "alternateMobileNumber": 9724219114,
            "permanentAddress": {
                "address": "Manaki lakhani",
                "state": "ગુજરાત ",
                "mandal": "લાખણી ",
                "village": "માણકી ",
                "pincode": 385535,
                "mandaliNearAddress": "માણકી ",
                "_id": "6756e210e00b8ba21e409bd3"
            },
            "internetProvider": "12",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:26:56.795Z",
            "updatedAt": "2024-12-09T12:26:56.795Z",
            "__v": 0
        },
        {
            "_id": "6756e211e00b8ba21e409bd5",
            "employeeId": "none",
            "title": "Dr.",
            "firstName": "Haradanji",
            "middleName": "Venaji",
            "lastName": "Chudhary ",
            "email": "",
            "mobileNumber": 9724219114,
            "alternateMobileNumber": 9724219114,
            "permanentAddress": {
                "address": "Manaki lakhani",
                "state": "ગુજરાત ",
                "mandal": "લાખણી ",
                "village": "માણકી ",
                "pincode": 385535,
                "mandaliNearAddress": "માણકી ",
                "_id": "6756e211e00b8ba21e409bd6"
            },
            "internetProvider": "12",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:26:57.101Z",
            "updatedAt": "2024-12-09T12:26:57.101Z",
            "__v": 0
        },
        {
            "_id": "6756e27de00b8ba21e409bd8",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "Prajapati Vijaybhai manabhai ",
            "middleName": "Prajapati manabhai hardasbhai ",
            "lastName": "Prajapati ",
            "email": "vijayprajapati3407@gmail.com",
            "mobileNumber": 7359163407,
            "alternateMobileNumber": 9428539751,
            "permanentAddress": {
                "address": "Sardarpura ",
                "state": "Gujarat",
                "mandal": "Wav",
                "village": "Sardarpura ",
                "pincode": 385575,
                "mandaliNearAddress": "",
                "_id": "6756e27de00b8ba21e409bd9"
            },
            "internetProvider": "12",
            "wifiExpense": "above 1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T12:28:45.690Z",
            "updatedAt": "2024-12-09T12:28:45.690Z",
            "__v": 0
        },
        {
            "_id": "6756e2b4e00b8ba21e409bdb",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": " Aniruddhsinh",
            "middleName": "Dhudubha ",
            "lastName": "Vaghela",
            "email": "www.aniruddhsinh30@gmail.com",
            "mobileNumber": 992438983,
            "alternateMobileNumber": 8200239672,
            "permanentAddress": {
                "address": "Thara Sadubhapati",
                "state": "Gujarat",
                "mandal": "KANKAREJ ",
                "village": "Thara sadubhapati ",
                "pincode": 385555,
                "mandaliNearAddress": "Sadujivas ",
                "_id": "6756e2b4e00b8ba21e409bdc"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:29:40.242Z",
            "updatedAt": "2024-12-09T12:29:40.242Z",
            "__v": 0
        },
        {
            "_id": "6756e304e00b8ba21e409bde",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "VIKRAMSINH",
            "middleName": "SAVJIBHAI",
            "lastName": "CHAUHAN",
            "email": "chuhanvikram264@gmail.com",
            "mobileNumber": 9714002715,
            "alternateMobileNumber": 7490060900,
            "permanentAddress": {
                "address": "Kuvana",
                "state": "Gujarat",
                "mandal": "lakhani",
                "village": "kuvana",
                "pincode": 385535,
                "mandaliNearAddress": "kuvanagam",
                "_id": "6756e304e00b8ba21e409bdf"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:31:00.572Z",
            "updatedAt": "2024-12-09T12:31:00.572Z",
            "__v": 0
        },
        {
            "_id": "6756e32ee00b8ba21e409be1",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": " Aniruddhsinh",
            "middleName": "Dhudubha ",
            "lastName": "Vaghela",
            "email": "www.aniruddhsinh30@gmail.com",
            "mobileNumber": 992438983,
            "alternateMobileNumber": 8200239672,
            "permanentAddress": {
                "address": "Thara Sadubhapati",
                "state": "Gujarat",
                "mandal": "KANKAREJ ",
                "village": "Thara sadubhapati ",
                "pincode": 385555,
                "mandaliNearAddress": "Sadujivas ",
                "_id": "6756e32ee00b8ba21e409be2"
            },
            "internetProvider": "1",
            "wifiExpense": "200-500",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "3",
            "createdAt": "2024-12-09T12:31:42.680Z",
            "updatedAt": "2024-12-09T12:31:42.680Z",
            "__v": 0
        },
        {
            "_id": "6756e392e00b8ba21e409be4",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "laxmanbhai ",
            "middleName": "satrabhai",
            "lastName": "chaudhary",
            "email": "",
            "mobileNumber": 9427086126,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "jasra",
                "state": "gujrat",
                "mandal": "lakhani",
                "village": "jasra",
                "pincode": 38535,
                "mandaliNearAddress": "chaudhary vas jasra",
                "_id": "6756e392e00b8ba21e409be5"
            },
            "internetProvider": "12",
            "wifiExpense": "above 1000",
            "wifiRecharge": "12",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T12:33:22.893Z",
            "updatedAt": "2024-12-09T12:33:22.893Z",
            "__v": 0
        },
        {
            "_id": "6756e43be00b8ba21e409be7",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Jaydevbhai",
            "middleName": "Rajaram",
            "lastName": "Joshi",
            "email": "jaydevjoshi96@gmail.com",
            "mobileNumber": 9979369348,
            "alternateMobileNumber": 9725469348,
            "permanentAddress": {
                "address": "Nani",
                "state": "Gujrat ",
                "mandal": "LAkhani ",
                "village": "Nani",
                "pincode": 385310,
                "mandaliNearAddress": "",
                "_id": "6756e43be00b8ba21e409be8"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:36:11.818Z",
            "updatedAt": "2024-12-09T12:36:11.818Z",
            "__v": 0
        },
        {
            "_id": "6756e4aae00b8ba21e409bea",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "Laxmanbhai",
            "middleName": "Satrabhai",
            "lastName": "Chaudhari",
            "email": "laxmansp01@gmail.com",
            "mobileNumber": 942708612,
            "alternateMobileNumber": 9427086126,
            "permanentAddress": {
                "address": "Jasara\nLakhani",
                "state": "Gujarat",
                "mandal": "Jasara ",
                "village": "Jasara ",
                "pincode": 385535,
                "mandaliNearAddress": "Chaudharivas jasara ",
                "_id": "6756e4aae00b8ba21e409beb"
            },
            "internetProvider": "12",
            "wifiExpense": "above 1000",
            "wifiRecharge": "12",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T12:38:02.253Z",
            "updatedAt": "2024-12-09T12:38:02.253Z",
            "__v": 0
        },
        {
            "_id": "6756e596e00b8ba21e409bed",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "Balakrishna",
            "middleName": "Ramarao",
            "lastName": "Nandamuri",
            "email": "bk@nan.com",
            "mobileNumber": 9809898909,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "Jublee Hills, Hyderabad",
                "state": "Telangana",
                "mandal": "Hyderabad",
                "village": "Hyderabad",
                "pincode": 500032,
                "mandaliNearAddress": "Hyderabad",
                "_id": "6756e596e00b8ba21e409bee"
            },
            "internetProvider": "1",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:41:58.958Z",
            "updatedAt": "2024-12-09T12:41:58.958Z",
            "__v": 0
        },
        {
            "_id": "6756e59ce00b8ba21e409bf0",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "kajabhai ",
            "middleName": "dhudabhai",
            "lastName": "patel",
            "email": "",
            "mobileNumber": 9428677091,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "jasra",
                "state": "gujrat",
                "mandal": "lakhani",
                "village": "jasa",
                "pincode": 385535,
                "mandaliNearAddress": "chaudhary vas jasra",
                "_id": "6756e59ce00b8ba21e409bf1"
            },
            "internetProvider": "1",
            "wifiExpense": "above 1000",
            "wifiRecharge": "12",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T12:42:04.461Z",
            "updatedAt": "2024-12-09T12:42:04.461Z",
            "__v": 0
        },
        {
            "_id": "6756e5ede00b8ba21e409bf3",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "Ratubhai ",
            "middleName": "Moghjibhai",
            "lastName": "Patel",
            "email": "patelratu78@gmail.com",
            "mobileNumber": 9825210923,
            "alternateMobileNumber": 9426310923,
            "permanentAddress": {
                "address": "Arbudanagar, saklana Ta: vadgam\nDist : Banaskantha",
                "state": "Gujarat",
                "mandal": "Vadgam",
                "village": "Saklana",
                "pincode": 385421,
                "mandaliNearAddress": "Arbudanagar mahila dudh utpadak",
                "_id": "6756e5ede00b8ba21e409bf4"
            },
            "internetProvider": "3",
            "wifiExpense": "100-200",
            "wifiRecharge": "3",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:43:25.431Z",
            "updatedAt": "2024-12-09T12:43:25.431Z",
            "__v": 0
        },
        {
            "_id": "6756e5fde00b8ba21e409bf6",
            "employeeId": "none",
            "title": "Mr.",
            "firstName": "karthik",
            "middleName": "sarvan",
            "lastName": "sarvan",
            "email": "karthiks1mail@gmail.com",
            "mobileNumber": 6281858488,
            "alternateMobileNumber": 6281858488,
            "permanentAddress": {
                "address": "mk royal apartments",
                "state": "Andhra Pradesh",
                "mandal": "dont know",
                "village": "vizag",
                "pincode": 531173,
                "mandaliNearAddress": "",
                "_id": "6756e5fde00b8ba21e409bf7"
            },
            "internetProvider": "3",
            "wifiExpense": "500-1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:43:41.765Z",
            "updatedAt": "2024-12-09T12:43:41.765Z",
            "__v": 0
        },
        {
            "_id": "6756e668e00b8ba21e409bf9",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "gordhanbhai",
            "middleName": "dhudabhai",
            "lastName": "patel",
            "email": "",
            "mobileNumber": 9925179007,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "jasra\n",
                "state": "gujrat",
                "mandal": "lakhani",
                "village": "jasra",
                "pincode": 385535,
                "mandaliNearAddress": "chaudhary vas jasra",
                "_id": "6756e668e00b8ba21e409bfa"
            },
            "internetProvider": "12",
            "wifiExpense": "above 1000",
            "wifiRecharge": "12",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T12:45:28.832Z",
            "updatedAt": "2024-12-09T12:45:28.832Z",
            "__v": 0
        },
        {
            "_id": "6756e6c1e00b8ba21e409c04",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Nagarjuna",
            "middleName": "",
            "lastName": "akkineni",
            "email": "nag@aki.com",
            "mobileNumber": 9809089000,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "jubleehills",
                "state": "tel",
                "mandal": "hyd",
                "village": "hyd",
                "pincode": 890890,
                "mandaliNearAddress": "hyd",
                "_id": "6756e6c1e00b8ba21e409c05"
            },
            "internetProvider": "4",
            "wifiExpense": "500-1000",
            "wifiRecharge": "2",
            "currentInternetPlanValidity": "5",
            "createdAt": "2024-12-09T12:46:57.050Z",
            "updatedAt": "2024-12-09T12:46:57.050Z",
            "__v": 0
        },
        {
            "_id": "6756e6e1e00b8ba21e409c07",
            "employeeId": "employee",
            "title": "Mr.",
            "firstName": "Jayeshkumar ",
            "middleName": "Chelabhai",
            "lastName": "Chaudhary",
            "email": "",
            "mobileNumber": 9638070412,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "At- Gadalvada,Ta- Palanpur,dist.- Palanpur - 380501",
                "state": "Gujarat",
                "mandal": "Palanpur",
                "village": "Gadalvada",
                "pincode": 380501,
                "mandaliNearAddress": "Gadalvada milk produce Mandali",
                "_id": "6756e6e1e00b8ba21e409c08"
            },
            "internetProvider": "1",
            "wifiExpense": "500-1000",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "1",
            "createdAt": "2024-12-09T12:47:29.649Z",
            "updatedAt": "2024-12-09T12:47:29.649Z",
            "__v": 0
        },
        {
            "_id": "6756e716e00b8ba21e409c0a",
            "employeeId": "milk-pourer",
            "title": "Mrs.",
            "firstName": "KARSHANBHAI ",
            "middleName": "PABUJI ",
            "lastName": "Patel ",
            "email": "",
            "mobileNumber": 9016152800,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "AT-POST-GHANA ",
                "state": "Gujarat",
                "mandal": "Lakhani",
                "village": "Ghana ",
                "pincode": 385310,
                "mandaliNearAddress": "Jadiyali ",
                "_id": "6756e716e00b8ba21e409c0b"
            },
            "internetProvider": "12",
            "wifiExpense": "100-200",
            "wifiRecharge": "1",
            "currentInternetPlanValidity": "12",
            "createdAt": "2024-12-09T12:48:22.303Z",
            "updatedAt": "2024-12-09T12:48:22.303Z",
            "__v": 0
        },
        {
            "_id": "6756e71ce00b8ba21e409c0d",
            "employeeId": "milk-pourer",
            "title": "Mr.",
            "firstName": "hemrajbhai",
            "middleName": "kalyanbhai",
            "lastName": "patel",
            "email": "",
            "mobileNumber": 9428845993,
            "alternateMobileNumber": null,
            "permanentAddress": {
                "address": "jasra",
                "state": "gujrat",
                "mandal": "lakhani",
                "village": "jasra",
                "pincode": 385535,
                "mandaliNearAddress": "chaydhary as jasra",
                "_id": "6756e71ce00b8ba21e409c0e"
            },
            "internetProvider": "3",
            "wifiExpense": "500-1000",
            "wifiRecharge": "3",
            "currentInternetPlanValidity": "3",
            "createdAt": "2024-12-09T12:48:28.498Z",
            "updatedAt": "2024-12-09T12:48:28.498Z",
            "__v": 0
        }
    ]
}

console.log(data.data.length)